- name: Redeploy frontend
  run: |
    aws ecs update-service \
      --cluster project-cluster \
      --service frontend \
      --force-new-deployment

- name: Redeploy link-service
  run: |
    aws ecs update-service \
      --cluster project-cluster \
      --service link-service \
      --force-new-deployment

- name: Redeploy analytics-service
  run: |
    aws ecs update-service \
      --cluster project-cluster \
      --service analytics-service \
      --force-new-deployment
